### ISSUE TITLE
Gravity Forms WP Plugin - Conditional Logic not working

### ISSUE THREAD

**Issue by henkvalk** [bentideswell/magento2-wordpress-integration#126]
Hi, 

I installed the Gravity Forms and want to show it inside Magento as a Page. When I add it, some functionality of GF isn't working anymore. Like Sections, Conditional Logic etc. 

How can I use the javascript / css of the Gravity Forms extension with the M2WP integration ?

**Comment by bentideswell** [comment]
Hi Henk,

For plugins like Gravity Forms to work, you will need the following add-on module:

[Shortcodes & Widgets](https://fishpig.co.uk/magento/wordpress-integration/shortcodes-widgets/)

This add-on module allows plugins that use shortodes to function when WP is integrated into Magento.

This module has evolved since it was first released and named and now does more than just shortcodes and widgets. It adds support for most WP plugins, RSS feed, XML sitemaps and a lot more WP features. A better name for this module in it's current state would 'Magento 2 WordPress Integration Pro' as it adds a next level of integration than the free module.

This is an add-on module for the free module though, so you still need the free/core module installed and also updated to the latest version.
