### ISSUE TITLE
Don't attempt to auto-install theme on front-end requests

### ISSUE THREAD

**Issue by scottsb** [bentideswell/magento2-wordpress-integration#66]
The module attempts to validate that the WordPress theme is both **installed** and **installable** on every front-end request. Beyond adding unnecessary overhead to check that every request, it requires that the WordPress code files be writeable by the Magento web server user. While that permission check is reasonable for an install/setup request initiated through the admin, it should not be necessary simply to load a WordPress page. For security it makes sense (and is in fact officially recommended by Magento) that source code not be writeable by the web server user, but if you follow that best practice, then the module currently silently breaks due to the permission check.

**Comment by bentideswell** [comment]
Hi Scott, thanks for the feedback.

I have modified the theme installation/update service to only work when WordPress is loaded via the Admin. Currently this is limited to the configuration page for the module.

The latest version now performs a single check on the style.css file to determine whether the theme needs to be updated, rather than just updating each file regardless of whether it is required.

I will close this issue but please re-open if any have any more issues relating to this the theme.

**Comment by scottsb** [comment]
@bentideswell is that in a released version?

Looking at master here:

`Controller/Router::match()` calls
`Model/App::canRun()` calls
`Model/App::_init()` calls
`Helper/Theme::validate()`

And `validate()` checks the permissions and attempts to auto-install the theme.

**Comment by bentideswell** [comment]
Sorry, this release didn't get pushed out. I've just manually pushed it and it should be available now.
