### ISSUE TITLE
Magento 2 Extensions files are not being used at all.

### ISSUE THREAD

**Issue by abrorAbdullaev** [bentideswell/magento2-wordpress-integration#67]
I have installed the extension Fishpig_WordPress. My wordpress is in url pub/wordpress/
I have configured my server to access the url pub/wordpress/
The server is nginx.

The theme fishpig have been successfully installed in admin and activated in WP admin.
My site_url: mydomain.com/pub/wordpress
My hoome_url: mydomain.com/blog
The message in magento admin says that the blog is ready to use in mydomain.com/blog
but when I open it I see only the bare post list from WP, no theme from magento.

https://ibb.co/dnnMQG

I have checked whether the magento 2 extension is being used at all. Have inserted some die() in constructors of router.php, action.php and other relevant files and find out that those files are not being called at all.

P.S.
The links with guides are leading to 404.
i.e. https://fishpig.co.uk/magento/wordpress-integration/nginx/

**Comment by bentideswell** [comment]
This area is for bugs with the extension and not for specific configuration/installation queries. Those should be sent via the support form at https://fishpig.co.uk/magento-2/wordpress-integration/.

When contacting using the support form, please include a URL so that I can see the issue. This will make resolving your problem much quicker.

Also include whether you have any FishPig add-on modules installed.
