### ISSUE TITLE
Changes not showing in frontend

### ISSUE THREAD

**Issue by CharanjeetE** [bentideswell/magento2-wordpress-integration#83]
I integrated wordpress blog into magento site.When i try to update my blog in wordpress it is not showing in magento frontend.Blog is showing but not changes and updates in posts.Changes take effect only in database but not in frontend.Please help me what i am missing.

**Comment by bentideswell** [comment]
This is not the place for site specific configuration issues. This is for bugs within the module. I will close this. Please submit your request to help@fishpig.co.uk.

Your issue is likely caused because you have an FPC installed in Magento 2 that is stopping changes in WordPress from displaying on the frontend.
