### ISSUE TITLE
Alternative method of patching translations

### ISSUE THREAD

**Issue by tylerssn** [bentideswell/magento2-wordpress-integration#90]
Our production instance locks down our app so that only media, static and var directories are writable. This causes `coreTest::patchMagento()` to throw an exception in production because it cannot write to `vendor/magento/framework/Phrase/__.php`.

What is the purpose of this patch and how do we work within our constraints?

**Comment by bentideswell** [comment]
This patch occurs because both Magento and WordPress declare the __ translation function (eg. __('Some String') ) and in PHP, it's not possible to declare multiple functions with the same name.

A small modification is made to WordPress to wrap the WP __ function with a call to function_exists. This ensures that when WordPress is included in Magento, WordPress doesn't redeclare this function and uses the Magento function instead.

A small modification is then required in Magento to ensure that the translation function works in both Magento and WordPress. This modification checks for a global variable and if set, casts the return type to a string:

    if (isset($GLOBALS['phrase_as_string'])) {
      return (string)new \Magento\Framework\Phrase($text, $argc);
    }

    return new \Magento\Framework\Phrase($text, $argc);

This global variable is set when execution is transferred to WordPress and is required because WordPress uses the translation function to set array keys and without this modification, the array key would be set as a Phrase object and objects cannot be array keys.

I previously submitted a very simple pull request [here](https://github.com/magento/magento2/pull/19756) that allowed this change to be made without patching Magento files but this was rejected (unfairly in my opinion). As a result, this patch is required for integration. Feel free to request that Magento accept my pull request or find a way for the translation function to be customised (like most other parts of Magento 2).

Before trying to write to a file, FishPig\WordPress\Model\Integration\CoreTest checks whether the patch has already been made and if it has, it doesn't try to repatch. This means that you can apply the patch in your dev/staging environment and commit it to your code base so that the code deployed to live is already patched and does not need write permissions.

**Comment by tylerssn** [comment]
I agree. I'm not sure their perspective is valid.

I needed to get your module working in producing without it manipulating my locked down files. I was able to accomplish that with a Magento module,  (all contained within a composer package) the gist of which is:

1. Remove magento/framework's registration.php from Composers autoloader via[mcaskill/composer-exclude-files] (https://packagist.org/packages/mcaskill/composer-exclude-files). This is because we need the FishPig patched translator to be loaded before the Magento framework package is registered. 
2. Within the modules registration.php, include the FishPig patches translator followed by including Magento framework's registration.php.
   - We've now given our translator priority
3. Modify the `patchMagento()` to drop the core file patch tests.
4. One install step is added. The dev must add an `"exclude-from-files"` property to the root composer.json that points to `vendor/magento/framework/registration.php`

If this is of interest to you, I'm happy to share the package with you. I am happy to convert it to a PR as well, but I'm not likely to get around to it very soon.

**Comment by bentideswell** [comment]
That Composer package is really interesting.

It's difficult though because Magento provides 2 different methods of instaling modules (why?!) and these scripts only fire if the module is installed via Composer. If the module is installed in the app/code directory then these scripts don't fire. This means that I would need 2 separate mechanisms, one for each installation method, to patch Magento.

Your solution sounds awesome though and I will definitely keep it in mind.

 I will keep trying to find a single solution to solve this problem that doesn't require write access.
